project_id = "ltsjhyqjtssroftxjvht"

[functions.mpesa-reconcile]
verify_jwt = false

[functions.mpesa-egress-check]
verify_jwt = false

[functions.mpesa-proxy-verify]
verify_jwt = false

[functions.mpesa-callback]
verify_jwt = false


